version: '3'
services:
  nodejsapp: 
    image: 655040030455.dkr.ecr.eu-central-1.amazonaws.com/nodejsapp:1.1
    ports:
     - 3000:3000
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db   #host-volume-name   path-inside-of-the-container
  mongo-express:
    image: mongo-express
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:       #List all the volumes you are using in any of you container
  mongo-data:    # name of volume 
    driver: local   #additional information for docker to create that pysocal storage on local file system
